Feat/projects page
ITSeed-Official/itseed_frontend pull request #34
Opened 2022-02-27 12:59 UTC by AlanSyue

# Description
Create a new projects page.

## Followed up
- Need to discuss with the `[mentor information component](https://app.asana.com/0/1200963218344861/1201889627075445/f)`
- Need to discuss how to [redirect the page using anchor when clicking the next page component](https://app.asana.com/0/1200963218344861/1201889716532291/f).

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] You can test it in the development environment. [link](https://stage.itseed.tw/projects)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-02-27 15:34 UTC, Nick0603 requested changes
The path for Navigation ( or named by Header) is not updated to new path `/projects` with the feature.

2022-02-27 15:34 UTC, Nick0603 commented on components/templates/Projects/CareerEvents/CareerEvents.module.scss
> +    float: left;
I think the style attribute is redundant.

2022-02-27 15:34 UTC, Nick0603 commented on components/templates/Projects/CareerEvents/CareerEvents.tsx
> +              屆職涯召部團隊也舉辦了一系列的職涯活動，以四大核心價值「分享、回饋、回顧、前瞻」，來協助學員在不同的產業與職務能有更深入的了解，盡情探索各種未來方向，並成為更具有競爭力的市場人才，以此籌畫了各類型職涯活動！
Why does this split line here?

2022-02-27 15:34 UTC, Nick0603 commented on components/templates/Projects/index.tsx
> +        onTabClick={(tab: ProjectName) => {
The activeTab style is not working now.

I think it is caused by the detection mechanism that I use `tav.activeTab` to match `tab.text`.

You can solve it by
1. Use the tab text to the anchor name

2. Extend the TabNav component to know how to match key for active tab.

2022-02-27 15:34 UTC, Nick0603 commented on components/templates/Projects/index.tsx
> +                <NextSection title="職涯專案" path="/projects#career" />
The page no handle for hash change event, so it's nothing to happed when user click NextSection component.

Solutions:
1. Add onClick property to  NextSection component, and let the `NextSection` prefer to use onClick than using `path` to change.

2. Add a `hash change event` for the page, and don't change `set

2022-03-13 06:11 UTC, AlanSyue commented on components/templates/Projects/CareerEvents/CareerEvents.tsx
> +              屆職涯召部團隊也舉辦了一系列的職涯活動，以四大核心價值「分享、回饋、回顧、前瞻」，來協助學員在不同的產業與職務能有更深入的了解，盡情探索各種未來方向，並成為更具有競爭力的市場人才，以此籌畫了各類型職涯活動！
It is split by the `yarn format:write`

2022-03-19 06:27 UTC, Nick0603 approved these changes
LGTM

2022-03-19 06:27 UTC, merged