Feat/homepage
ITSeed-Official/itseed_frontend pull request #7
Opened 2021-10-21 06:22 UTC by Malik705017

# Description

Complete homepage wireframe

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Open http://localhost:3000/
![截圖 2021-10-21 下午2 22 08](https://user-images.githubusercontent.com/45000964/138222455-f04bd033-b943-4ddb-9987-eb41bbbadf05.png)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-11-04 07:37 UTC, Malik705017 commented
@Nick0603 @AlanSyue 再麻煩你們幫我 review，thx!

2021-11-06 07:00 UTC, AlanSyue commented on styles/Home.module.scss
> +    aspect-ratio: 1 / 1;
[curiosity]
Do `1 / 1` need to be declared?

2021-11-06 07:01 UTC, AlanSyue approved these changes

2021-11-06 17:28 UTC, Nick0603 requested changes
Maybe we need to have a meeting to discuss.

2021-11-06 17:28 UTC, Nick0603 commented on components/atoms/Card/index.module.scss
> +@import "../../../styles/variables.scss";
Structure Discussion:

The file naming of `index.tsx` and `index.module.scss` are not easy to know the file content directly.

For example, if I search some keyword and result is `all index files`
![image](https://user-images.githubusercontent.com/16770691/140617675-84ae2eb7-0968-4448-bd70-c333314bc152.png)

The solution is like `hello-world` component. We define the all files are starting from `hello-world`
![image](https://user-images.githubusercontent.com/16770691/140617723-67cce75c-a1d9-4f66-8772-1bb12464a8b1.png)

And export in index file, and we can easy to know what are exported.
![image](https://user-images.githubusercontent.com/16770691/140617726-136c6495-fdb2-4a95-9e8f-819e862f56ff.png)

2021-11-06 17:28 UTC, Nick0603 commented on components/molecules/BannerContainer/index.tsx
> +export default BannerContainer;
The `BannerContainer` can implemented by `SectionWrapper`.

2021-11-06 17:28 UTC, Nick0603 commented on styles/mixin.scss
> +}
Make easier to read.
Can write the variables to global variables.scss
The logic of `desktop` here looks like a `laptop` logic. 


```suggestion
$width-desktop: 1960px;
$width-laptop: 1440px;
$width-large-tablet: 1024px;
$width-tablet: 768px;

@mixin laptop{
  @media(max-width: ($width-desktop - 1px)){
    @content;
  }
}

@mixin large-tablet{
  @media(max-width: ($width-laptop - 1px)){
    @content;
  }
}

@mixin tablet{
  @media(max-width: ($width-large-tablet - 1px)){
    @content;
  }
}

@mixin mobile{
  @media(max-width: ($width-tablet - 1px)){
      @content;
  }
}

```

2021-11-06 17:28 UTC, Nick0603 commented on components/molecules/BannerContainer/index.tsx
> +    <>
Redundant code

2021-11-15 03:25 UTC, Nick0603 reviewed
Some suggestions

2021-11-15 03:25 UTC, Nick0603 commented on components/atoms/CollapseBox/CollapseBox.tsx
> +          isOpen ? styles.open : styles.close
Seem no `close` key in styles?

2021-11-15 03:25 UTC, Nick0603 commented on components/atoms/CollapseBox/CollapseBox.tsx
> +          src={isOpen ? arrowUp : arrowDown}
[minor]
Would you like to make a rotation animation for it?
If you want it, you can use same image and set `transform: rotate(180deg)`

2021-11-15 03:25 UTC, Nick0603 commented on pages/index.tsx
> +      <BannerContainer backgroundImage="images/Banner-Homepage.png" />
The image naming is weird. How do we use `snake case` for it?

2021-11-15 03:25 UTC, Nick0603 commented on pages/index.tsx
> +import BannerContainer from "../components/molecules/BannerContainer/BannerContainer";
Add `index.tsx` for each component to make clear for exporter and make easier for imoprter.

```suggestion
import Button from "../components/atoms/Button";
import { SubTitle } from "../components/atoms/SectionTitle";
import Card from "../components/atoms/Card";
import CollapseBox from "../components/atoms/CollapseBox";
import SectionWrapper from "../components/molecules/SectionWrapper";
import BannerContainer from "../components/molecules/BannerContainer";
```

2021-11-15 09:04 UTC, Nick0603 approved these changes
LGTM

2021-11-15 09:07 UTC, merged